version: 2
jobs:
  build:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: Update System Packages
          command: apt-get update
      - run:
          name: Install System Packages
          command: apt-get install -y wget zip
      - run:
          name: Install Python Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Download Pickled Place Titles
          command: |
            cd /tmp
            wget https://s3.amazonaws.com/firstdraftgis/place_titles.pickle.zip
            unzip place_titles.pickle.zip
      - run:
          name: Create Counter
          command: python3 create_data.py
          no_output_timeout: 5h
      - run:
          name: Create TSV
          command: python3 create_tsv.py
      - run:
          name: Create Frequency Count
          command: python3 create_freq.py          
      - run:
          name: Run Test
          command: python3 test.py
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade
      - run:
          name: Zip Training Data
          command: zip -r /tmp/is_a_place_training_data.tsv.zip /tmp/is_a_place_training_data.tsv
      - run:
          name: Upload Training Data to S3
          command: aws s3 cp /tmp/is_a_place_training_data.tsv.zip s3://firstdraftgis/is_a_place_training_data.tsv.zip --acl public-read
      - run:
          name: Upload Pickles to S3
          command: |
            aws s3 cp /tmp/is_a_place_counter.pickle s3://firstdraftgis/is_a_place_counter.pickle --acl public-read
            aws s3 cp /tmp/is_a_place_frequency.pickle s3://firstdraftgis/is_a_place_frequency.pickle --acl public-read
      - run:
          name: Upload TSV to S3
          command: aws s3 cp /tmp/is_a_place.tsv s3://firstdraftgis/is_a_place.tsv --acl public-read